# -*- coding: utf-8 -*-
"""CyFuture_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11n4F9moONTsDwODIuNGXzI0jVXS1vHNq
"""

!pip install -q diffusers transformers accelerate scipy safetensors gradio

from huggingface_hub import login
login()  # 🔑 Paste your token here when prompted

import torch
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    safety_checker=None
).to(device)

import gradio as gr

def generate(prompt):
    image = pipe(prompt, guidance_scale=7.5, num_inference_steps=50).images[0]
    return image

gr.Interface(
    fn=generate,
    inputs=gr.Textbox(label="Enter your image prompt"),
    outputs=gr.Image(label="Generated Image"),
    title="Stable Diffusion - Text to Image"
).launch(share=True)  # ✅ share=True is important for Colab